#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonartez.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class Sonartez_server : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblActivityLog(TblActivityLog instance);
    partial void UpdateTblActivityLog(TblActivityLog instance);
    partial void DeleteTblActivityLog(TblActivityLog instance);
    partial void InsertTblClient(TblClient instance);
    partial void UpdateTblClient(TblClient instance);
    partial void DeleteTblClient(TblClient instance);
    partial void InsertTblConsultantLog(TblConsultantLog instance);
    partial void UpdateTblConsultantLog(TblConsultantLog instance);
    partial void DeleteTblConsultantLog(TblConsultantLog instance);
    partial void InsertTblInfor(TblInfor instance);
    partial void UpdateTblInfor(TblInfor instance);
    partial void DeleteTblInfor(TblInfor instance);
    partial void InsertTblPermission(TblPermission instance);
    partial void UpdateTblPermission(TblPermission instance);
    partial void DeleteTblPermission(TblPermission instance);
    partial void InsertTblUpdate(TblUpdate instance);
    partial void UpdateTblUpdate(TblUpdate instance);
    partial void DeleteTblUpdate(TblUpdate instance);
    partial void InsertTblUser(TblUser instance);
    partial void UpdateTblUser(TblUser instance);
    partial void DeleteTblUser(TblUser instance);
    partial void InsertTblUserPermission(TblUserPermission instance);
    partial void UpdateTblUserPermission(TblUserPermission instance);
    partial void DeleteTblUserPermission(TblUserPermission instance);
    #endregion
		
		public Sonartez_server(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sonartez_server(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sonartez_server(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sonartez_server(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblActivityLog> TblActivityLog
		{
			get
			{
				return this.GetTable<TblActivityLog>();
			}
		}
		
		public System.Data.Linq.Table<TblClient> TblClient
		{
			get
			{
				return this.GetTable<TblClient>();
			}
		}
		
		public System.Data.Linq.Table<TblConsultantLog> TblConsultantLog
		{
			get
			{
				return this.GetTable<TblConsultantLog>();
			}
		}
		
		public System.Data.Linq.Table<TblInfor> TblInfor
		{
			get
			{
				return this.GetTable<TblInfor>();
			}
		}
		
		public System.Data.Linq.Table<TblPermission> TblPermission
		{
			get
			{
				return this.GetTable<TblPermission>();
			}
		}
		
		public System.Data.Linq.Table<TblUpdate> TblUpdate
		{
			get
			{
				return this.GetTable<TblUpdate>();
			}
		}
		
		public System.Data.Linq.Table<TblUser> TblUser
		{
			get
			{
				return this.GetTable<TblUser>();
			}
		}
		
		public System.Data.Linq.Table<TblUserPermission> TblUserPermission
		{
			get
			{
				return this.GetTable<TblUserPermission>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblActivityLog")]
	public partial class TblActivityLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ActivityType;
		
		private System.Nullable<System.Guid> _UserID;
		
		private string _UserName;
		
		private System.Nullable<System.Guid> _ClientID;
		
		private string _ClientName;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _Descriptions;

        private System.Nullable<int> _IsDeleted;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnActivityTypeChanging(string value);
    partial void OnActivityTypeChanged();
    partial void OnUserIDChanging(System.Nullable<System.Guid> value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnClientIDChanging(System.Nullable<System.Guid> value);
    partial void OnClientIDChanged();
    partial void OnClientNameChanging(string value);
    partial void OnClientNameChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnDescriptionsChanging(string value);
    partial void OnDescriptionsChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblActivityLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDeleted", DbType = "Int")]
        public System.Nullable<int> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                if ((this._IsDeleted != value))
                {
                    this.OnIsDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._IsDeleted = value;
                    this.SendPropertyChanged("IsDeleted");
                    this.OnIsDeletedChanged();
                }
            }
        }

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityType", DbType="NVarChar(150)")]
		public string ActivityType
		{
			get
			{
				return this._ActivityType;
			}
			set
			{
				if ((this._ActivityType != value))
				{
					this.OnActivityTypeChanging(value);
					this.SendPropertyChanging();
					this._ActivityType = value;
					this.SendPropertyChanged("ActivityType");
					this.OnActivityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(150)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this.OnClientNameChanging(value);
					this.SendPropertyChanging();
					this._ClientName = value;
					this.SendPropertyChanged("ClientName");
					this.OnClientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptions", DbType="NVarChar(250)")]
		public string Descriptions
		{
			get
			{
				return this._Descriptions;
			}
			set
			{
				if ((this._Descriptions != value))
				{
					this.OnDescriptionsChanging(value);
					this.SendPropertyChanging();
					this._Descriptions = value;
					this.SendPropertyChanged("Descriptions");
					this.OnDescriptionsChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }

		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblClient")]
	public partial class TblClient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ClientID;
		
		private string _ClientName;
		
		private string _ClientCode;
		
		private string _LocationCode;
		
		private string _LocationName;
		
		private string _Descriptions;
		
		private System.Nullable<System.DateTime> _UpdateDate;

        private System.Nullable<int> _IsDeleted;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientIDChanging(System.Guid value);
    partial void OnClientIDChanged();
    partial void OnClientNameChanging(string value);
    partial void OnClientNameChanged();
    partial void OnClientCodeChanging(string value);
    partial void OnClientCodeChanged();
    partial void OnLocationCodeChanging(string value);
    partial void OnLocationCodeChanged();
    partial void OnLocationNameChanging(string value);
    partial void OnLocationNameChanged();
    partial void OnDescriptionsChanging(string value);
    partial void OnDescriptionsChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblClient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDeleted", DbType = "Int")]
        public System.Nullable<int> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                if ((this._IsDeleted != value))
                {
                    this.OnIsDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._IsDeleted = value;
                    this.SendPropertyChanged("IsDeleted");
                    this.OnIsDeletedChanged();
                }
            }
        }
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(150)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this.OnClientNameChanging(value);
					this.SendPropertyChanging();
					this._ClientName = value;
					this.SendPropertyChanged("ClientName");
					this.OnClientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientCode", DbType="NVarChar(50)")]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this.OnClientCodeChanging(value);
					this.SendPropertyChanging();
					this._ClientCode = value;
					this.SendPropertyChanged("ClientCode");
					this.OnClientCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCode", DbType="NVarChar(50)")]
		public string LocationCode
		{
			get
			{
				return this._LocationCode;
			}
			set
			{
				if ((this._LocationCode != value))
				{
					this.OnLocationCodeChanging(value);
					this.SendPropertyChanging();
					this._LocationCode = value;
					this.SendPropertyChanged("LocationCode");
					this.OnLocationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="NVarChar(150)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this.OnLocationNameChanging(value);
					this.SendPropertyChanging();
					this._LocationName = value;
					this.SendPropertyChanged("LocationName");
					this.OnLocationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptions", DbType="NVarChar(500)")]
		public string Descriptions
		{
			get
			{
				return this._Descriptions;
			}
			set
			{
				if ((this._Descriptions != value))
				{
					this.OnDescriptionsChanging(value);
					this.SendPropertyChanging();
					this._Descriptions = value;
					this.SendPropertyChanged("Descriptions");
					this.OnDescriptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblConsultantLog")]
	public partial class TblConsultantLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _ConsType;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _FinishDate;
		
		private string _FinishType;
		
		private System.Nullable<System.DateTime> _SubmitDate;
		
		private string _Status;
		
		private System.Nullable<System.Guid> _ClientID;
		
		private string _ClientCode;
		
		private string _ClientName;
		
		private System.Nullable<System.Guid> _UserID;
		
		private string _UserName;
		
		private string _TargetType;
		
		private string _TargetName;
		
		private string _TargetPhoneNumber;
		
		private string _TargetEmail;
		
		private string _TargetCountry;
		
		private System.Nullable<int> _TargetCount;
		
		private string _Question;
		
		private string _AnswerRef;
		
		private string _Descriptions;
		
		private System.Nullable<System.DateTime> _UpdateDate;

        private System.Nullable<int> _IsDeleted;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnConsTypeChanging(string value);
    partial void OnConsTypeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnFinishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishDateChanged();
    partial void OnFinishTypeChanging(string value);
    partial void OnFinishTypeChanged();
    partial void OnSubmitDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmitDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnClientIDChanging(System.Nullable<System.Guid> value);
    partial void OnClientIDChanged();
    partial void OnClientCodeChanging(string value);
    partial void OnClientCodeChanged();
    partial void OnClientNameChanging(string value);
    partial void OnClientNameChanged();
    partial void OnUserIDChanging(System.Nullable<System.Guid> value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTargetTypeChanging(string value);
    partial void OnTargetTypeChanged();
    partial void OnTargetNameChanging(string value);
    partial void OnTargetNameChanged();
    partial void OnTargetPhoneNumberChanging(string value);
    partial void OnTargetPhoneNumberChanged();
    partial void OnTargetEmailChanging(string value);
    partial void OnTargetEmailChanged();
    partial void OnTargetCountryChanging(string value);
    partial void OnTargetCountryChanged();
    partial void OnTargetCountChanging(System.Nullable<int> value);
    partial void OnTargetCountChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAnswerRefChanging(string value);
    partial void OnAnswerRefChanged();
    partial void OnDescriptionsChanging(string value);
    partial void OnDescriptionsChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblConsultantLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDeleted", DbType = "Int")]
        public System.Nullable<int> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                if ((this._IsDeleted != value))
                {
                    this.OnIsDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._IsDeleted = value;
                    this.SendPropertyChanged("IsDeleted");
                    this.OnIsDeletedChanged();
                }
            }
        }

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsType", DbType="NVarChar(50)")]
		public string ConsType
		{
			get
			{
				return this._ConsType;
			}
			set
			{
				if ((this._ConsType != value))
				{
					this.OnConsTypeChanging(value);
					this.SendPropertyChanging();
					this._ConsType = value;
					this.SendPropertyChanged("ConsType");
					this.OnConsTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishDate
		{
			get
			{
				return this._FinishDate;
			}
			set
			{
				if ((this._FinishDate != value))
				{
					this.OnFinishDateChanging(value);
					this.SendPropertyChanging();
					this._FinishDate = value;
					this.SendPropertyChanged("FinishDate");
					this.OnFinishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishType", DbType="NVarChar(50)")]
		public string FinishType
		{
			get
			{
				return this._FinishType;
			}
			set
			{
				if ((this._FinishType != value))
				{
					this.OnFinishTypeChanging(value);
					this.SendPropertyChanging();
					this._FinishType = value;
					this.SendPropertyChanged("FinishType");
					this.OnFinishTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmitDate
		{
			get
			{
				return this._SubmitDate;
			}
			set
			{
				if ((this._SubmitDate != value))
				{
					this.OnSubmitDateChanging(value);
					this.SendPropertyChanging();
					this._SubmitDate = value;
					this.SendPropertyChanged("SubmitDate");
					this.OnSubmitDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientCode", DbType="NVarChar(50)")]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this.OnClientCodeChanging(value);
					this.SendPropertyChanging();
					this._ClientCode = value;
					this.SendPropertyChanged("ClientCode");
					this.OnClientCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(50)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this.OnClientNameChanging(value);
					this.SendPropertyChanging();
					this._ClientName = value;
					this.SendPropertyChanged("ClientName");
					this.OnClientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetType", DbType="NVarChar(50)")]
		public string TargetType
		{
			get
			{
				return this._TargetType;
			}
			set
			{
				if ((this._TargetType != value))
				{
					this.OnTargetTypeChanging(value);
					this.SendPropertyChanging();
					this._TargetType = value;
					this.SendPropertyChanged("TargetType");
					this.OnTargetTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetName", DbType="NVarChar(250)")]
		public string TargetName
		{
			get
			{
				return this._TargetName;
			}
			set
			{
				if ((this._TargetName != value))
				{
					this.OnTargetNameChanging(value);
					this.SendPropertyChanging();
					this._TargetName = value;
					this.SendPropertyChanged("TargetName");
					this.OnTargetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetPhoneNumber", DbType="NVarChar(50)")]
		public string TargetPhoneNumber
		{
			get
			{
				return this._TargetPhoneNumber;
			}
			set
			{
				if ((this._TargetPhoneNumber != value))
				{
					this.OnTargetPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._TargetPhoneNumber = value;
					this.SendPropertyChanged("TargetPhoneNumber");
					this.OnTargetPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetEmail", DbType="NVarChar(150)")]
		public string TargetEmail
		{
			get
			{
				return this._TargetEmail;
			}
			set
			{
				if ((this._TargetEmail != value))
				{
					this.OnTargetEmailChanging(value);
					this.SendPropertyChanging();
					this._TargetEmail = value;
					this.SendPropertyChanged("TargetEmail");
					this.OnTargetEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetCountry", DbType="NVarChar(50)")]
		public string TargetCountry
		{
			get
			{
				return this._TargetCountry;
			}
			set
			{
				if ((this._TargetCountry != value))
				{
					this.OnTargetCountryChanging(value);
					this.SendPropertyChanging();
					this._TargetCountry = value;
					this.SendPropertyChanged("TargetCountry");
					this.OnTargetCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetCount", DbType="Int")]
		public System.Nullable<int> TargetCount
		{
			get
			{
				return this._TargetCount;
			}
			set
			{
				if ((this._TargetCount != value))
				{
					this.OnTargetCountChanging(value);
					this.SendPropertyChanging();
					this._TargetCount = value;
					this.SendPropertyChanged("TargetCount");
					this.OnTargetCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(500)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerRef", DbType="NVarChar(250)")]
		public string AnswerRef
		{
			get
			{
				return this._AnswerRef;
			}
			set
			{
				if ((this._AnswerRef != value))
				{
					this.OnAnswerRefChanging(value);
					this.SendPropertyChanging();
					this._AnswerRef = value;
					this.SendPropertyChanged("AnswerRef");
					this.OnAnswerRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptions", DbType="NVarChar(500)")]
		public string Descriptions
		{
			get
			{
				return this._Descriptions;
			}
			set
			{
				if ((this._Descriptions != value))
				{
					this.OnDescriptionsChanging(value);
					this.SendPropertyChanging();
					this._Descriptions = value;
					this.SendPropertyChanged("Descriptions");
					this.OnDescriptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblInfor")]
	public partial class TblInfor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _InfoTitle;
		
		private string _InfoContent;

        private string _InfoContentHtml;
		
		private string _InfoTag;
		
		private System.Nullable<System.Guid> _CreateUserID;
		
		private System.Nullable<System.Guid> _UpdateUserID;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _Status;
		
		private string _InfoType;

        private string _Location;

        private string _Category;
		
		private System.Nullable<System.DateTime> _BeginDate;
		
		private System.Nullable<System.DateTime> _ExprieDate;

        private System.Nullable<int> _IsDeleted;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnInfoTitleChanging(string value);
    partial void OnInfoTitleChanged();
    partial void OnInfoContentChanging(string value);
    partial void OnInfoContentChanged();
    partial void OnInfoContentHtmlChanging(string value);
    partial void OnInfoContentHtmlChanged();
    partial void OnInfoTagChanging(string value);
    partial void OnInfoTagChanged();
    partial void OnCreateUserIDChanging(System.Nullable<System.Guid> value);
    partial void OnCreateUserIDChanged();
    partial void OnUpdateUserIDChanging(System.Nullable<System.Guid> value);
    partial void OnUpdateUserIDChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnInfoTypeChanging(string value);
    partial void OnInfoTypeChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnBeginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBeginDateChanged();
    partial void OnExprieDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExprieDateChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblInfor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoTitle", DbType="NVarChar(250)")]
		public string InfoTitle
		{
			get
			{
				return this._InfoTitle;
			}
			set
			{
				if ((this._InfoTitle != value))
				{
					this.OnInfoTitleChanging(value);
					this.SendPropertyChanging();
					this._InfoTitle = value;
					this.SendPropertyChanged("InfoTitle");
					this.OnInfoTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoContent", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string InfoContent
		{
			get
			{
				return this._InfoContent;
			}
			set
			{
				if ((this._InfoContent != value))
				{
					this.OnInfoContentChanging(value);
					this.SendPropertyChanging();
					this._InfoContent = value;
					this.SendPropertyChanged("InfoContent");
					this.OnInfoContentChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_InfoContentHtml", DbType = "NText", UpdateCheck = UpdateCheck.Never)]
        public string InfoContentHtml
        {
            get
            {
                return this._InfoContentHtml;
            }
            set
            {
                if ((this._InfoContentHtml != value))
                {
                    this.OnInfoContentHtmlChanging(value);
                    this.SendPropertyChanging();
                    this._InfoContentHtml = value;
                    this.SendPropertyChanged("InfoContentHtml");
                    this.OnInfoContentHtmlChanged();
                }
            }
        }
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoTag", DbType="NVarChar(250)")]
		public string InfoTag
		{
			get
			{
				return this._InfoTag;
			}
			set
			{
				if ((this._InfoTag != value))
				{
					this.OnInfoTagChanging(value);
					this.SendPropertyChanging();
					this._InfoTag = value;
					this.SendPropertyChanged("InfoTag");
					this.OnInfoTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpdateUserID
		{
			get
			{
				return this._UpdateUserID;
			}
			set
			{
				if ((this._UpdateUserID != value))
				{
					this.OnUpdateUserIDChanging(value);
					this.SendPropertyChanging();
					this._UpdateUserID = value;
					this.SendPropertyChanged("UpdateUserID");
					this.OnUpdateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoType", DbType="NVarChar(50)")]
		public string InfoType
		{
			get
			{
				return this._InfoType;
			}
			set
			{
				if ((this._InfoType != value))
				{
					this.OnInfoTypeChanging(value);
					this.SendPropertyChanging();
					this._InfoType = value;
					this.SendPropertyChanged("InfoType");
					this.OnInfoTypeChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Location", DbType = "NVarChar(100)")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                if ((this._Location != value))
                {
                    this.OnLocationChanging(value);
                    this.SendPropertyChanging();
                    this._Location = value;
                    this.SendPropertyChanged("Location");
                    this.OnLocationChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Category", DbType = "NVarChar(200)")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                if ((this._Category != value))
                {
                    this.OnCategoryChanging(value);
                    this.SendPropertyChanging();
                    this._Category = value;
                    this.SendPropertyChanged("Category");
                    this.OnCategoryChanged();
                }
            }
        }

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BeginDate
		{
			get
			{
				return this._BeginDate;
			}
			set
			{
				if ((this._BeginDate != value))
				{
					this.OnBeginDateChanging(value);
					this.SendPropertyChanging();
					this._BeginDate = value;
					this.SendPropertyChanged("BeginDate");
					this.OnBeginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExprieDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExprieDate
		{
			get
			{
				return this._ExprieDate;
			}
			set
			{
				if ((this._ExprieDate != value))
				{
					this.OnExprieDateChanging(value);
					this.SendPropertyChanging();
					this._ExprieDate = value;
					this.SendPropertyChanged("ExprieDate");
					this.OnExprieDateChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDeleted", DbType = "Int")]
        public System.Nullable<int> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                if ((this._IsDeleted != value))
                {
                    this.OnIsDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._IsDeleted = value;
                    this.SendPropertyChanged("IsDeleted");
                    this.OnIsDeletedChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblPermission")]
	public partial class TblPermission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PermissionCode;
		
		private string _PermissionName;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPermissionCodeChanging(string value);
    partial void OnPermissionCodeChanged();
    partial void OnPermissionNameChanging(string value);
    partial void OnPermissionNameChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblPermission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PermissionCode
		{
			get
			{
				return this._PermissionCode;
			}
			set
			{
				if ((this._PermissionCode != value))
				{
					this.OnPermissionCodeChanging(value);
					this.SendPropertyChanging();
					this._PermissionCode = value;
					this.SendPropertyChanged("PermissionCode");
					this.OnPermissionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionName", DbType="NVarChar(250)")]
		public string PermissionName
		{
			get
			{
				return this._PermissionName;
			}
			set
			{
				if ((this._PermissionName != value))
				{
					this.OnPermissionNameChanging(value);
					this.SendPropertyChanging();
					this._PermissionName = value;
					this.SendPropertyChanged("PermissionName");
					this.OnPermissionNameChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblUpdate")]
	public partial class TblUpdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _LastConsutantUpdate;
		
		private System.Nullable<System.DateTime> _LastInfoUpdate;
		
		private System.Nullable<System.DateTime> _LastUserUpdate;
		
		private System.Nullable<System.DateTime> _LastClientUpdate;
		
		private System.Nullable<System.DateTime> _LastUserPermissionUpdate;
		
		private System.Nullable<System.DateTime> _LastActivityLogUpdate;

        private System.Nullable<System.DateTime> _LocalConsutantUpdate;

        private System.Nullable<System.DateTime> _LocalInfoUpdate;

        private System.Nullable<System.DateTime> _LocalUserUpdate;

        private System.Nullable<System.DateTime> _LocalClientUpdate;

        private System.Nullable<System.DateTime> _LocalActivityLogUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLastConsutantUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastConsutantUpdateChanged();
    partial void OnLastInfoUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastInfoUpdateChanged();
    partial void OnLastUserUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUserUpdateChanged();
    partial void OnLastClientUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastClientUpdateChanged();
    partial void OnLastUserPermissionUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUserPermissionUpdateChanged();
    partial void OnLastActivityLogUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityLogUpdateChanged();

    partial void OnLocalConsutantUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLocalConsutantUpdateChanged();
    partial void OnLocalInfoUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLocalInfoUpdateChanged();
    partial void OnLocalUserUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLocalUserUpdateChanged();
    partial void OnLocalClientUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLocalClientUpdateChanged();
    partial void OnLocalActivityLogUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLocalActivityLogUpdateChanged();
    #endregion
		
		public TblUpdate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastConsutantUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastConsutantUpdate
		{
			get
			{
				return this._LastConsutantUpdate;
			}
			set
			{
				if ((this._LastConsutantUpdate != value))
				{
					this.OnLastConsutantUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastConsutantUpdate = value;
					this.SendPropertyChanged("LastConsutantUpdate");
					this.OnLastConsutantUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastInfoUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastInfoUpdate
		{
			get
			{
				return this._LastInfoUpdate;
			}
			set
			{
				if ((this._LastInfoUpdate != value))
				{
					this.OnLastInfoUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastInfoUpdate = value;
					this.SendPropertyChanged("LastInfoUpdate");
					this.OnLastInfoUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUserUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUserUpdate
		{
			get
			{
				return this._LastUserUpdate;
			}
			set
			{
				if ((this._LastUserUpdate != value))
				{
					this.OnLastUserUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUserUpdate = value;
					this.SendPropertyChanged("LastUserUpdate");
					this.OnLastUserUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastClientUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastClientUpdate
		{
			get
			{
				return this._LastClientUpdate;
			}
			set
			{
				if ((this._LastClientUpdate != value))
				{
					this.OnLastClientUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastClientUpdate = value;
					this.SendPropertyChanged("LastClientUpdate");
					this.OnLastClientUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUserPermissionUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUserPermissionUpdate
		{
			get
			{
				return this._LastUserPermissionUpdate;
			}
			set
			{
				if ((this._LastUserPermissionUpdate != value))
				{
					this.OnLastUserPermissionUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUserPermissionUpdate = value;
					this.SendPropertyChanged("LastUserPermissionUpdate");
					this.OnLastUserPermissionUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityLogUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivityLogUpdate
		{
			get
			{
				return this._LastActivityLogUpdate;
			}
			set
			{
				if ((this._LastActivityLogUpdate != value))
				{
					this.OnLastActivityLogUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityLogUpdate = value;
					this.SendPropertyChanged("LastActivityLogUpdate");
					this.OnLastActivityLogUpdateChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocalConsutantUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> LocalConsutantUpdate
        {
            get
            {
                return this._LocalConsutantUpdate;
            }
            set
            {
                if ((this._LocalConsutantUpdate != value))
                {
                    this.OnLocalConsutantUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._LocalConsutantUpdate = value;
                    this.SendPropertyChanged("LocalConsutantUpdate");
                    this.OnLocalConsutantUpdateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocalInfoUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> LocalInfoUpdate
        {
            get
            {
                return this._LocalInfoUpdate;
            }
            set
            {
                if ((this._LocalInfoUpdate != value))
                {
                    this.OnLocalInfoUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._LocalInfoUpdate = value;
                    this.SendPropertyChanged("LocalInfoUpdate");
                    this.OnLocalInfoUpdateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocalUserUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> LocalUserUpdate
        {
            get
            {
                return this._LocalUserUpdate;
            }
            set
            {
                if ((this._LocalUserUpdate != value))
                {
                    this.OnLocalUserUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._LocalUserUpdate = value;
                    this.SendPropertyChanged("LocalUserUpdate");
                    this.OnLocalUserUpdateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocalClientUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> LocalClientUpdate
        {
            get
            {
                return this._LocalClientUpdate;
            }
            set
            {
                if ((this._LocalClientUpdate != value))
                {
                    this.OnLocalClientUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._LocalClientUpdate = value;
                    this.SendPropertyChanged("LocalClientUpdate");
                    this.OnLocalClientUpdateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LocalActivityLogUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> LocalActivityLogUpdate
        {
            get
            {
                return this._LocalActivityLogUpdate;
            }
            set
            {
                if ((this._LocalActivityLogUpdate != value))
                {
                    this.OnLocalActivityLogUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._LocalActivityLogUpdate = value;
                    this.SendPropertyChanged("LocalActivityLogUpdate");
                    this.OnLocalActivityLogUpdateChanged();
                }
            }
        }

		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblUser")]
	public partial class TblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserID;
		
		private string _UserName;
		
		private string _FullName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Password;

        private string _Permission;
		
		private System.Nullable<System.DateTime> _LastLoginTime;
		
		private System.Nullable<int> _Active;

        private System.Nullable<int> _IsDeleted;
		
		private System.Nullable<System.DateTime> _UpdateDate;

        private System.Nullable<System.DateTime> _ServerUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPermissionChanging(string value);
    partial void OnPermissionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLastLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginTimeChanged();
    partial void OnActiveChanging(System.Nullable<int> value);
    partial void OnActiveChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Permission", DbType = "NVarChar(20)")]
        public string Permission
        {
            get
            {
                return this._Permission;
            }
            set
            {
                if ((this._Permission != value))
                {
                    this.OnPasswordChanging(value);
                    this.SendPropertyChanging();
                    this._Permission = value;
                    this.SendPropertyChanged("Permission");
                    this.OnPermissionChanged();
                }
            }
        }
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginTime
		{
			get
			{
				return this._LastLoginTime;
			}
			set
			{
				if ((this._LastLoginTime != value))
				{
					this.OnLastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LastLoginTime = value;
					this.SendPropertyChanged("LastLoginTime");
					this.OnLastLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int")]
		public System.Nullable<int> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDeleted", DbType = "Int")]
        public System.Nullable<int> IsDeleted
		{
			get
			{
                return this._IsDeleted;
			}
			set
			{
                if ((this._IsDeleted != value))
				{
                    this.OnIsDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._IsDeleted = value;
                    this.SendPropertyChanged("IsDeleted");
                    this.OnIsDeletedChanged();
				}
			}
		}
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

       
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tblUserPermission")]
	public partial class TblUserPermission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.Guid> _UserID;
		
		private string _PermissionID;
		
		private string _PermissionName;
		
		private System.Nullable<System.DateTime> _UpdateTime;

        private System.Nullable<System.DateTime> _ServerUpdate;

     
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(System.Nullable<System.Guid> value);
    partial void OnUserIDChanged();
    partial void OnPermissionIDChanging(string value);
    partial void OnPermissionIDChanged();
    partial void OnPermissionNameChanging(string value);
    partial void OnPermissionNameChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnServerUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnServerUpdateChanged();
    #endregion
		
		public TblUserPermission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="NVarChar(10)")]
		public string PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this.OnPermissionIDChanging(value);
					this.SendPropertyChanging();
					this._PermissionID = value;
					this.SendPropertyChanged("PermissionID");
					this.OnPermissionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionName", DbType="NVarChar(250)")]
		public string PermissionName
		{
			get
			{
				return this._PermissionName;
			}
			set
			{
				if ((this._PermissionName != value))
				{
					this.OnPermissionNameChanging(value);
					this.SendPropertyChanging();
					this._PermissionName = value;
					this.SendPropertyChanged("PermissionName");
					this.OnPermissionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServerUpdate", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ServerUpdate
        {
            get
            {
                return this._ServerUpdate;
            }
            set
            {
                if ((this._ServerUpdate != value))
                {
                    this.OnServerUpdateChanging(value);
                    this.SendPropertyChanging();
                    this._ServerUpdate = value;
                    this.SendPropertyChanged("ServerUpdate");
                    this.OnServerUpdateChanged();
                }
            }
        }
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
